import { InMemoryCheckInsRepository } from '@/repositories/in-memory/in-memory-check-ins-repository'
import { ResourceNotFoundError } from '@/use-cases/errors/resource-not-found-error'
import {
  expect,
  describe,
  it,
  beforeEach,
  afterEach,
  TestContext,
  vi,
} from 'vitest'
import { ValidateCheckInUseCase } from './validate-check-in'

interface contextProps extends TestContext {
  checkInsRepository: InMemoryCheckInsRepository
  sut: ValidateCheckInUseCase
}

describe('Validate Check-in Use Case', () => {
  beforeEach(async (context: contextProps) => {
    context.checkInsRepository = new InMemoryCheckInsRepository()
    context.sut = new ValidateCheckInUseCase(context.checkInsRepository)

    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('should be able to validate the check-in', async ({
    checkInsRepository,
    sut,
  }: contextProps) => {
    const createdCheckIn = await checkInsRepository.create({
      gym_id: 'gym-01',
      user_id: 'user-01',
    })

    const { checkIn } = await sut.execute({
      checkInId: createdCheckIn.id,
    })

    expect(checkIn.validated_at).toEqual(expect.any(Date))
    expect(checkInsRepository.items[0].validated_at).toEqual(expect.any(Date))
  })

  it('should not be able to validate an inexistent check-in', async ({
    sut,
  }: contextProps) => {
    await expect(() =>
      sut.execute({
        checkInId: 'inexistent-check-in-id',
      }),
    ).rejects.toBeInstanceOf(ResourceNotFoundError)
  })

  it('should not be able to validate the check-in after 20 minutes of its creation', async ({
    checkInsRepository,
    sut,
  }: contextProps) => {
    vi.setSystemTime(new Date(2023, 0, 1, 13, 40))

    const createdCheckIn = await checkInsRepository.create({
      gym_id: 'gym-01',
      user_id: 'user-01',
    })

    const twentyOneMinutesInMs = 1000 * 60 * 21

    vi.advanceTimersByTime(twentyOneMinutesInMs)

    await expect(() =>
      sut.execute({
        checkInId: createdCheckIn.id,
      }),
    ).rejects.toBeInstanceOf(Error)
  })
})
